"use client";
import Link from "next/link";
import { useState } from "react";
import { ArrowRight, BarChart3, CheckCircle2, ChevronRight, Eye, Menu, Monitor, Play, QrCode, Radio, Smartphone, Sparkles, Trophy, Users, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { CuePopLogo } from "@/components/logo";
import { Reveal } from "@/components/marketing/reveal";

export function LandingPage(){const [menu,setMenu]=useState(false);return <main className="overflow-hidden bg-[#01021d] text-white">
 <header className="fixed inset-x-0 top-0 z-50 border-b border-white/[.06] bg-black/70 backdrop-blur-xl"><div className="cue-container flex h-16 items-center"><Link href="/"><CuePopLogo/></Link><nav className="ml-12 hidden items-center gap-7 text-sm text-[#a1a1a1] md:flex"><a href="#product" className="hover:text-white">Product</a><a href="#how" className="hover:text-white">How it works</a><a href="#use-cases" className="hover:text-white">Use cases</a><a href="#keepsake" className="hover:text-white">Keepsake</a></nav><div className="ml-auto hidden items-center gap-2 md:flex"><Button asChild variant="ghost" size="sm"><Link href="/login">Sign in</Link></Button><Button asChild size="sm"><Link href="/register">Create a live deck</Link></Button></div><button onClick={()=>setMenu(!menu)} aria-label={menu?"Close menu":"Open menu"} aria-expanded={menu} className="ml-auto md:hidden">{menu?<X className="size-5"/>:<Menu className="size-5"/>}</button></div>{menu&&<div className="cue-container border-t border-white/[.06] py-4 md:hidden"><div className="grid gap-3 text-sm text-[#a1a1a1]"><a onClick={()=>setMenu(false)} href="#product">Product</a><a onClick={()=>setMenu(false)} href="#how">How it works</a><a onClick={()=>setMenu(false)} href="#use-cases">Use cases</a><Button asChild className="mt-2"><Link href="/register">Create a live deck</Link></Button></div></div>}</header>

 <section className="relative overflow-hidden pt-44 pb-24"><img src="/art/hero-glow.png" alt="" aria-hidden="true" className="absolute inset-x-0 top-0 z-0 h-[780px] w-full object-cover opacity-90"/><div className="absolute inset-x-0 top-0 z-[1] h-[780px] opacity-[.09] mix-blend-screen" style={{backgroundImage:"var(--grain)",backgroundSize:"140px 140px"}}/><div className="absolute inset-x-0 top-0 z-[1] h-[780px] bg-gradient-to-b from-transparent via-transparent to-[#01021d]"/>
  <div className="cue-container relative z-10 text-center"><Reveal><p className="cue-eyebrow mx-auto">Live audience presentations</p><h1 className="cue-display mx-auto mt-6 max-w-3xl">Turn slides into a room that <span className="cue-gradient-text">responds.</span></h1><p className="cue-body mx-auto mt-6 max-w-[560px]">Upload slide images, insert polls and quizzes, and control exactly when the room joins, responds and sees the result.</p><div className="mt-8 flex flex-wrap justify-center gap-3"><Button asChild size="lg"><Link href="/register">Create a live deck<ArrowRight className="size-4"/></Link></Button><Button asChild size="lg" variant="secondary"><Link href="/login">Open working demo<Play className="size-4"/></Link></Button></div><p className="mt-5 text-xs text-[#7d7d7d]">Demo account: demo@cuepop.app · demo1234</p></Reveal></div>
  <Reveal delay={.12}><div className="cue-container relative z-10 mt-16"><div className="cue-panel grid gap-8 p-8 sm:grid-cols-3 sm:p-10">
   <HeroStat value="4" label="Live surfaces — host, stage, remote, attendee"/>
   <HeroStat value="<2 min" label="From upload to a running session"/>
   <HeroStat value="0" label="Accounts required to join"/>
  </div></div></Reveal>
 </section>

 <section id="product" className="relative overflow-hidden cue-section pt-8"><img src="/art/product-glow.png" alt="" aria-hidden="true" className="absolute inset-0 h-full w-full object-cover opacity-60"/><div className="absolute inset-0 bg-gradient-to-l from-[#01021d]/35 via-[#01021d]/70 to-[#01021d]"/><div className="absolute inset-x-0 top-0 h-1/3 bg-gradient-to-b from-[#01021d] to-transparent"/><div className="absolute inset-x-0 bottom-0 h-1/3 bg-gradient-to-t from-[#01021d] to-transparent"/><div className="cue-container relative z-10"><div className="grid items-start gap-16 lg:grid-cols-2"><Reveal><p className="cue-eyebrow">Your deck, now live</p><h2 className="cue-heading mt-6">Upload the deck.<br/>Control the room.</h2><p className="cue-body mt-6 max-w-md">CuePop keeps the workflow image-first: upload, arrange, insert a moment and present. No PowerPoint plugin and no audience account wall.</p></Reveal><Reveal delay={.1}><div className="cue-panel p-8"><div className="space-y-5"><CheckLine>Upload PNG, JPEG, WebP or GIF slides directly</CheckLine><CheckLine>Insert a poll or quiz between any two slides</CheckLine><CheckLine>Reorder the timeline by dragging storyboard items</CheckLine><CheckLine>Autosaves as you go, with nothing to publish separately</CheckLine></div></div></Reveal></div><div className="mt-14 grid gap-4 md:grid-cols-2"><Reveal><FeatureCard icon={QrCode} title="Dynamic join" copy="A live, readable join page—not a QR image buried inside a slide." index={0}/></Reveal><Reveal delay={.08}><FeatureCard icon={Eye} title="Controlled reveal" copy="Close responses first. Reveal the room only when the presenter chooses." index={1}/></Reveal></div></div></section>

 <section id="how" className="relative overflow-hidden cue-section"><img src="/art/how-glow.png" alt="" aria-hidden="true" className="absolute inset-0 h-full w-full object-cover opacity-85"/><div className="absolute inset-0 bg-gradient-to-r from-transparent via-[#01021d]/30 to-[#01021d]/70"/><div className="absolute inset-x-0 top-0 h-1/4 bg-gradient-to-b from-[#01021d] to-transparent"/><div className="absolute inset-x-0 bottom-0 h-1/2 bg-gradient-to-b from-transparent to-[#01021d]"/><div className="cue-container relative z-10"><Reveal className="ml-auto max-w-xl"><p className="cue-eyebrow">Run the room</p><h2 className="cue-heading mt-6">Present confidently.<br/>Control every moment.</h2><p className="cue-body mt-6">One host timeline synchronizes the projector, attendee phones and a compact remote without exposing private controls to the room.</p></Reveal><div className="mt-14 grid gap-4 md:grid-cols-3">{runControls.map((item,index)=><Reveal key={item.title} delay={index*.06}><FeatureCard {...item} index={index}/></Reveal>)}</div></div></section>

 <section className="relative overflow-hidden cue-section"><img src="/art/surfaces-glow.png" alt="" aria-hidden="true" className="absolute inset-0 h-full w-full object-cover opacity-80"/><div className="absolute inset-0 bg-gradient-to-r from-transparent via-[#01021d]/20 to-[#01021d]/85"/><div className="absolute inset-x-0 top-0 h-1/4 bg-gradient-to-b from-[#01021d] to-transparent"/><div className="absolute inset-x-0 bottom-0 h-1/3 bg-gradient-to-t from-[#01021d] to-transparent"/><div className="cue-container relative z-10"><Reveal className="ml-auto max-w-lg text-right"><h2 className="cue-heading">One session. Three perfectly timed views.</h2><p className="cue-body mt-6 ml-auto max-w-md">Each surface shows only what that person needs. Shared state, separate responsibilities.</p></Reveal><div className="mt-12 grid gap-4 md:grid-cols-3">{surfaces.map((item,index)=><Reveal key={item.title} delay={index*.06}><FeatureCard {...item} index={index}/></Reveal>)}</div></div></section>

 <section className="relative overflow-hidden cue-section"><img src="/art/moment-glow.png" alt="" aria-hidden="true" className="absolute inset-0 h-full w-full object-cover opacity-45"/><div className="absolute inset-0 bg-gradient-to-b from-[#01021d] via-[#01021d]/60 to-[#01021d]"/><div className="cue-container relative z-10"><Reveal className="mx-auto max-w-3xl text-center"><p className="cue-eyebrow mx-auto">Exact-moment interaction</p><h2 className="cue-heading mt-6">Open the question<br/>exactly when you choose.</h2><p className="cue-body mx-auto mt-6 max-w-2xl">Joining, voting, closing and revealing are separate actions, so the presenter—not the software—sets the pace.</p></Reveal><Reveal className="mt-14"><StateTimeline/></Reveal></div></section>

 <section id="keepsake" className="relative flex min-h-[92vh] items-center overflow-hidden py-24"><img src="/art/keepsake-glow.png" alt="" aria-hidden="true" className="absolute inset-0 h-full w-full object-cover opacity-85"/><div className="absolute inset-0 bg-gradient-to-r from-[#01021d]/70 via-[#01021d]/15 to-transparent"/><div className="absolute inset-x-0 top-0 h-1/4 bg-gradient-to-b from-[#01021d] to-transparent"/><div className="absolute inset-x-0 bottom-0 h-1/3 bg-gradient-to-t from-[#01021d] to-transparent"/><div className="cue-container relative z-10">
   <Reveal><p className="cue-eyebrow">A useful ending</p></Reveal>
   <Reveal delay={.1}><h2 className="cue-heading mt-7 whitespace-nowrap !font-normal italic">The session ends.<br/><span className="cue-gradient-text not-italic font-semibold">The connection stays.</span></h2></Reveal>
   <Reveal delay={.2}><div className="mt-8 h-px w-16 bg-gradient-to-r from-[var(--violet-strong)] to-transparent opacity-70"/></Reveal>
   <Reveal delay={.28}><p className="cue-body mt-8 max-w-md">Named attendees choose from curated designs and download a polished Session Keepsake Card. The host protects quality; the attendee keeps the memory.</p></Reveal>
   <Reveal delay={.36}><div className="mt-9 inline-flex flex-col gap-4 text-left"><CheckLine>Curated designs, not user-uploaded artwork</CheckLine><CheckLine>High-resolution PNG generated in the browser</CheckLine><CheckLine>Optional names and privacy-safe projector views</CheckLine></div></Reveal>
  </div></section>

 <section className="relative overflow-hidden cue-section"><img src="/art/templates-glow.png" alt="" aria-hidden="true" className="absolute inset-0 h-full w-full object-cover opacity-70"/><div className="absolute inset-x-0 top-0 h-1/4 bg-gradient-to-b from-[#01021d] to-transparent"/><div className="absolute inset-x-0 bottom-0 h-2/3 bg-gradient-to-t from-[#01021d] to-transparent"/><div className="cue-container relative z-10"><Reveal><p className="cue-eyebrow">Start with a moment</p><h2 className="cue-heading mt-6">Choose a format.<br/>Make it yours.</h2><p className="cue-body mt-6 max-w-md">Every template is a real state inside the same live timeline—not a disconnected widget. The poll is the one most rooms start with.</p></Reveal><div className="mt-12 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{templates.map((item,index)=><Reveal key={item.title} delay={index*.05}><TemplateCard {...item} index={index}/></Reveal>)}</div></div></section>

 <section id="use-cases" className="relative overflow-hidden cue-section"><img src="/art/use-cases-glow.png" alt="" aria-hidden="true" className="absolute inset-0 h-full w-full object-cover object-top opacity-75"/><div className="absolute inset-0 bg-gradient-to-b from-[#01021d] via-[#01021d]/45 to-[#01021d]"/><div className="cue-container relative z-10"><Reveal><p className="cue-eyebrow">Built for real rooms</p><h2 className="cue-heading mt-6">From a college hall<br/>to a team workshop.</h2></Reveal><div className="mt-14 grid gap-4 lg:grid-cols-3">{useCases.map((item,index)=><Reveal key={item.title} delay={index*.07}><div className="cue-hover-card cue-panel min-h-[280px] p-7"><div className="cue-hover-icon grid size-10 place-items-center rounded-lg border border-white/[.08] bg-white/[.03]"><item.icon className="size-4" style={{color:index%2===0?"var(--cyan-strong)":"var(--violet-strong)"}}/></div><div className="mt-14 text-xs font-semibold uppercase tracking-[.14em] text-[#7d7d7d]">0{index+1}</div><h3 className="mt-4 text-xl font-semibold tracking-[-.02em]">{item.title}</h3><p className="mt-4 text-sm leading-7 text-[#8a8a8a]">{item.copy}</p></div></Reveal>)}</div></div></section>

 <section className="relative overflow-hidden border-t border-white/[.06] py-24"><img src="/art/cta-glow.png" alt="" aria-hidden="true" className="absolute inset-0 h-full w-full object-cover opacity-50"/><div className="absolute inset-0 bg-gradient-to-t from-[#01021d] via-transparent to-[#01021d]/70"/><div className="cue-container relative z-10 text-center"><Reveal><h2 className="cue-heading">Make your next<br/>room respond.</h2><p className="cue-body mx-auto mt-6 max-w-xl">Create a deck, run a private dry test and experience the host, attendee, remote and stage views together.</p><div className="mt-8 flex justify-center gap-3"><Button asChild size="lg"><Link href="/register">Create a live deck<ArrowRight className="size-4"/></Link></Button><Button asChild variant="secondary" size="lg"><Link href="/login">Open demo</Link></Button></div></Reveal></div></section>
 <footer className="border-t border-white/[.06] py-8"><div className="cue-container flex flex-col items-center justify-between gap-4 text-xs text-[#7d7d7d] sm:flex-row"><CuePopLogo/><span>Image-first live presentations · Built for rooms that should respond.</span><span>© 2026 CuePop</span></div></footer>
 </main>}
function HeroStat({value,label}:{value:string;label:string}){return <div className="text-center sm:text-left"><div className="cue-gradient-text text-4xl font-semibold tracking-[-.03em]">{value}</div><div className="mt-2 text-sm leading-6 text-[#8a8a8a]">{label}</div></div>}
function FeatureCard({icon:Icon,title,copy,index=0}:{icon:typeof Smartphone;title:string;copy:string;index?:number}){const tone=index%2===0?"var(--cyan-strong)":"var(--violet-strong)";return <div className="cue-hover-card cue-panel min-h-[220px] p-7"><div className="cue-hover-icon grid size-10 place-items-center rounded-lg border border-white/[.08] bg-white/[.03]"><Icon className="size-4" style={{color:tone}}/></div><h3 className="mt-6 font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-[#8a8a8a]">{copy}</p></div>}
const runControls=[{icon:Radio,title:"Open on command",copy:"Start voting the moment you're ready—never automatically, never early."},{icon:Smartphone,title:"Phone remote",copy:"Move through slides, open voting, close responses and reveal results without returning to the laptop."},{icon:BarChart3,title:"Room response",copy:"Response counts update live while the projector stays clean, legible and anonymous."}];
const surfaces=[{icon:Monitor,title:"Stage",copy:"Projector-safe slides, QR, questions and results—never host controls or names."},{icon:Smartphone,title:"Attendee",copy:"Join, answer once and stay synchronized without an account or app."},{icon:Radio,title:"Host",copy:"Control pace, voting and reveal from a laptop or phone remote."}];
function StateTimeline(){const states=[{title:"Waiting",copy:"Attendees stay connected."},{title:"Active",copy:"One vote per person."},{title:"Submitted",copy:"Response is locked."},{title:"Closed",copy:"No new answers."},{title:"Revealed",copy:"Results reach the room."}];return <div className="cue-panel relative overflow-hidden p-6 md:p-10"><div className="relative grid gap-8 md:grid-cols-5">{states.map((state,index)=><div key={state.title} className="relative"><div className="flex items-center"><span className={`grid size-9 place-items-center rounded-full border text-xs font-semibold ${index===4?"border-[var(--cyan-strong)] bg-[rgba(65,105,225,.16)] text-[var(--cyan-strong)]":"border-white/[.1] text-[#8a8a8a]"}`}>{index+1}</span>{index<states.length-1&&<span className="hidden h-px flex-1 bg-white/[.08] md:block"/>}</div><h3 className="mt-5 font-semibold">{state.title}</h3><p className="mt-2 text-xs leading-5 text-[#7a7a7a]">{state.copy}</p></div>)}</div></div>}
function CheckLine({children}:{children:React.ReactNode}){return <div className="flex items-start gap-3 text-sm text-[#a1a1a1]"><CheckCircle2 className="mt-0.5 size-4 shrink-0 text-[var(--success)]"/>{children}</div>}
const templates=[{icon:QrCode,title:"Dynamic Join Screen",copy:"Live QR, short code, waiting message and join count."},{icon:BarChart3,title:"Multiple-choice Poll",copy:"Open, close and reveal the room on presenter command.",featured:true},{icon:Trophy,title:"Knowledge Quiz",copy:"Mark the correct answer and reveal it after voting."},{icon:Monitor,title:"Result Reveal",copy:"Projector-safe percentages with no attendee names."},{icon:Sparkles,title:"Session Keepsake",copy:"Three curated designs with high-resolution download."},{icon:Users,title:"Post-session Report",copy:"Participation rates and CSV-ready option totals."}];
function TemplateCard({icon:Icon,title,copy,featured,index=0}:{icon:typeof QrCode;title:string;copy:string;featured?:boolean;index?:number}){const tone=index%2===0?"var(--cyan-strong)":"var(--violet-strong)";return <div className={`group min-h-[200px] p-5 ${featured?"cue-glow-card":"cue-hover-card cue-panel"}`}><div className="flex items-center justify-between"><div className={`cue-hover-icon grid size-9 place-items-center rounded-lg border ${featured?"border-[rgba(65,105,225,.45)] bg-[rgba(65,105,225,.14)]":"border-white/[.08] bg-white/[.03]"}`}><Icon className="size-4" style={{color:featured?"var(--cyan-strong)":tone}}/></div>{featured?<span className="rounded-full bg-[var(--cyan)] px-2.5 py-1 text-[10px] font-semibold text-white">Most used</span>:<span className="grid size-8 place-items-center rounded-full border border-white/[.07] text-[#7d7d7d] transition-colors group-hover:text-white"><ChevronRight className="cue-hover-arrow size-3.5"/></span>}</div><h3 className="mt-8 font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-[#8a8a8a]">{copy}</p></div>}
const useCases=[{icon:Users,title:"College placement halls",copy:"Make a 100–1,000 person career session participatory without requiring an app or student accounts."},{icon:Trophy,title:"Trainers and workshops",copy:"Check understanding at the exact point it matters without breaking the facilitator’s rhythm."},{icon:Monitor,title:"Corporate learning events",copy:"Run a polished internal event with controlled stage output, remote operation and useful reporting."}];
