"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { AnimatePresence, motion } from "framer-motion";
import { ArrowLeft, BarChart3, GripVertical, Image as ImageIcon, LoaderCircle, MoreHorizontal, Play, Save, Settings2, Trash2, Trophy, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "@/components/ui/toaster";
import { FileDropzone } from "@/components/file-dropzone";
import { MomentEditor, type MomentDraft } from "@/components/moment-editor";
import type { Deck, DeckItem } from "@/lib/schema";
import { cn } from "@/lib/utils";

export function DeckBuilder({ initialDeck }: { initialDeck: Deck }) {
 const router=useRouter(); const [deck,setDeck]=useState(initialDeck); const [selectedId,setSelectedId]=useState(initialDeck.items?.[0]?.id||null); const [modal,setModal]=useState<null|"poll"|"quiz"|"settings">(null); const [saving,setSaving]=useState(false); const [starting,setStarting]=useState(false); const [dragId,setDragId]=useState<string|null>(null);
 const items=deck.items||[]; const selected=items.find(i=>i.id===selectedId)||items[0];
 async function api(url:string,options:RequestInit){const res=await fetch(url,options);const body=await res.json();if(!res.ok)throw new Error(body.error||"Request failed");return body.data}
 async function addSlide(file:{url:string;name:string}){const item=await api(`/api/decks/${deck.id}/items`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({type:"slide",title:file.name.replace(/\.[^.]+$/,""),imageUrl:file.url})});setDeck(d=>({...d,items:[...(d.items||[]),item]}));setSelectedId(item.id)}
 async function saveMoment(draft:MomentDraft){try{const item=await api(`/api/decks/${deck.id}/items`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(draft)});setDeck(d=>({...d,items:[...(d.items||[]),item]}));setSelectedId(item.id);setModal(null);toast({title:"Live moment inserted",description:"It is now part of the presentation timeline."})}catch(e){toast({title:"Could not add moment",description:e instanceof Error?e.message:"Try again",tone:"error"})}}
 async function updateItem(itemId:string,patch:Partial<DeckItem>){try{const item=await api(`/api/decks/${deck.id}/items/${itemId}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(patch)});setDeck(d=>({...d,items:(d.items||[]).map(i=>i.id===itemId?item:i)}));toast({title:"Changes saved"})}catch(e){toast({title:"Could not save",description:e instanceof Error?e.message:"Try again",tone:"error"})}}
 async function removeItem(itemId:string){if(!confirm("Remove this item from the deck?"))return;await api(`/api/decks/${deck.id}/items/${itemId}`,{method:"DELETE"});const next=items.filter(i=>i.id!==itemId).map((i,p)=>({...i,position:p}));setDeck(d=>({...d,items:next}));setSelectedId(next[0]?.id||null)}
 async function reorder(targetId:string){if(!dragId||dragId===targetId)return;const source=items.findIndex(i=>i.id===dragId);const target=items.findIndex(i=>i.id===targetId);const next=[...items];const [moved]=next.splice(source,1);next.splice(target,0,moved);const ordered=next.map((i,p)=>({...i,position:p}));setDeck(d=>({...d,items:ordered}));setDragId(null);try{await api(`/api/decks/${deck.id}/reorder`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({orderedIds:ordered.map(i=>i.id)})})}catch{toast({title:"Could not reorder",tone:"error"})}}
 async function saveSettings(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);try{const form=new FormData(e.currentTarget);const keepsakeThemes=form.getAll("keepsakeThemes").map(String);if(!keepsakeThemes.length)throw new Error("Choose at least one keepsake design.");const updated=await api(`/api/decks/${deck.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({title:form.get("title"),description:form.get("description"),waitingMessage:form.get("waitingMessage"),keepsakeThemes})});setDeck(d=>({...d,...updated}));setModal(null);toast({title:"Deck settings saved"})}catch(e){toast({title:"Could not save settings",description:e instanceof Error?e.message:"Try again",tone:"error"})}finally{setSaving(false)}}
 async function startLive(){if(items.length===0){toast({title:"Add at least one slide or moment",tone:"error"});return}setStarting(true);try{const data=await api("/api/live/start",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({deckId:deck.id})});router.push(`/present/${data.code}?token=${encodeURIComponent(data.controllerToken)}`)}catch(e){toast({title:"Could not start session",description:e instanceof Error?e.message:"Try again",tone:"error"})}finally{setStarting(false)}}
 return <div className="-m-4 min-h-[calc(100svh-64px)] md:-m-8 lg:-m-10">
  <header className="flex h-16 items-center gap-3 border-b border-white/[.065] bg-[#080a0d] px-4 md:px-6"><Button asChild size="icon" variant="ghost"><Link href="/workspace" aria-label="Back to workspace"><ArrowLeft className="size-4"/></Link></Button><div className="min-w-0"><div className="truncate text-sm font-semibold">{deck.title}</div><div className="text-[11px] text-[#68737d]">{items.length} timeline items · autosaved</div></div><div className="ml-auto flex items-center gap-2"><Button variant="ghost" size="sm" onClick={()=>setModal("settings")}><Settings2 className="size-4"/><span className="hidden sm:inline">Settings</span></Button><Button variant="accent" size="sm" onClick={startLive} disabled={starting}>{starting?<LoaderCircle className="size-4 animate-spin"/>:<Play className="size-4"/>}<span className="hidden sm:inline">Start live session</span></Button></div></header>
  <div className="grid min-h-[calc(100svh-128px)] lg:grid-cols-[294px_minmax(0,1fr)_330px]">
   <aside className="border-b border-white/[.065] bg-[#07090c] lg:border-b-0 lg:border-r"><div className="flex items-center justify-between px-4 py-4"><div><div className="text-xs font-semibold uppercase tracking-[.13em] text-[#69747f]">Storyboard</div><div className="mt-1 text-xs text-[#4f5963]">Drag to reorder</div></div><div className="flex gap-1"><Button size="icon" variant="ghost" onClick={()=>setModal("poll")} title="Add poll" aria-label="Add poll"><BarChart3 className="size-4"/></Button><Button size="icon" variant="ghost" onClick={()=>setModal("quiz")} title="Add quiz" aria-label="Add quiz"><Trophy className="size-4"/></Button></div></div>
    <div className="max-h-[48svh] space-y-2 overflow-y-auto px-3 pb-4 scrollbar-thin lg:max-h-[calc(100svh-320px)]">{items.map((item,index)=><button draggable onDragStart={()=>setDragId(item.id)} onDragOver={e=>e.preventDefault()} onDrop={()=>void reorder(item.id)} onClick={()=>setSelectedId(item.id)} key={item.id} className={cn("group flex w-full items-center gap-2 rounded-xl border p-2 text-left transition",selected?.id===item.id?"border-[rgba(77,127,224,.32)] bg-[rgba(77,127,224,.065)]":"border-transparent hover:border-white/[.06] hover:bg-white/[.03]")}><GripVertical className="size-3.5 shrink-0 text-[#4f5963]"/><div className="grid size-8 shrink-0 place-items-center rounded-lg border border-white/[.07] bg-[#101419] text-[10px] font-semibold text-[#8d98a3]">{item.type==="slide"?index+1:item.type==="quiz"?<Trophy className="size-3.5 text-[var(--violet)]"/>:<BarChart3 className="size-3.5 text-[var(--cyan)]"/>}</div><div className="min-w-0 flex-1"><div className="truncate text-xs font-medium text-[#d9dee3]">{item.title}</div><div className="mt-0.5 text-[10px] uppercase tracking-[.12em] text-[#5e6872]">{item.type}</div></div></button>)}</div>
    <div className="border-t border-white/[.06] p-3"><FileDropzone onUploaded={addSlide}/></div>
   </aside>
   <main className="relative flex min-h-[520px] items-center justify-center overflow-hidden bg-[#050608] p-5 md:p-10"><div className="absolute inset-0 cue-grid-noise opacity-30"/><div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_55%,rgba(77,127,224,.055),transparent_45%)]"/>{selected?<EditorCanvas item={selected}/>:<div className="relative max-w-sm text-center"><div className="mx-auto grid size-14 place-items-center rounded-2xl border border-white/[.08] bg-white/[.035]"><ImageIcon className="size-5 text-[var(--cyan)]"/></div><h2 className="mt-5 text-xl font-semibold">Start the timeline</h2><p className="mt-2 text-sm leading-6 text-[#737e89]">Upload a slide image, then insert polls or quizzes between slides.</p></div>}</main>
   <aside className="border-t border-white/[.065] bg-[#090b0f] lg:border-l lg:border-t-0">{selected?<Inspector item={selected} onUpdate={updateItem} onDelete={removeItem}/>:<div className="p-5 text-sm text-[#737e89]">Select an item to edit its title and presenter notes.</div>}</aside>
  </div>
  <AnimatePresence>{modal&&<Modal onClose={()=>setModal(null)}>{modal==="poll"||modal==="quiz"?<MomentEditor type={modal} onSave={saveMoment} onCancel={()=>setModal(null)}/>:<form onSubmit={saveSettings} className="space-y-5"><div><p className="cue-eyebrow">Deck settings</p><h3 className="mt-2 text-xl font-semibold">Prepare the room</h3></div><div className="space-y-2"><Label>Deck title</Label><Input name="title" defaultValue={deck.title}/></div><div className="space-y-2"><Label>Description</Label><Textarea name="description" defaultValue={deck.description}/></div><div className="space-y-2"><Label>Waiting message</Label><Textarea name="waitingMessage" defaultValue={deck.waitingMessage}/></div><div className="space-y-2"><Label>Keepsake designs attendees may choose</Label><div className="grid grid-cols-3 gap-2">{([['signal','Signal'],['midnight','Midnight'],['paper','Paper']] as const).map(([value,label])=><label key={value} className="flex cursor-pointer items-center gap-2 rounded-xl border border-white/[.08] bg-white/[.025] px-3 py-3 text-xs font-medium"><input type="checkbox" name="keepsakeThemes" value={value} defaultChecked={deck.keepsakeThemes.includes(value)} className="accent-[var(--cyan)]"/><span>{label}</span></label>)}</div><p className="text-xs leading-5 text-[#6f7a84]">Select one or more curated designs. Attendees only see these options after the session ends.</p></div><div className="flex justify-end gap-2"><Button type="button" variant="ghost" onClick={()=>setModal(null)}>Cancel</Button><Button type="submit" variant="accent" disabled={saving}>{saving?<LoaderCircle className="size-4 animate-spin"/>:<Save className="size-4"/>}Save settings</Button></div></form>}</Modal>}</AnimatePresence>
 </div>
}
function EditorCanvas({item}:{item:DeckItem}){if(item.type==="slide")return <div className="relative w-full max-w-5xl overflow-hidden rounded-2xl border border-white/[.1] bg-black shadow-[0_50px_140px_rgba(0,0,0,.65)] aspect-video">{item.imageUrl?<img src={item.imageUrl} alt={item.title} className="h-full w-full object-contain"/>:<div className="grid h-full place-items-center text-[#66717c]">Slide image unavailable</div>}</div>;return <div className="relative w-full max-w-5xl overflow-hidden rounded-2xl border border-white/[.09] bg-[#090c10] p-[clamp(24px,5vw,64px)] shadow-[0_50px_140px_rgba(0,0,0,.65)] aspect-video"><div className="absolute inset-0 bg-[radial-gradient(circle_at_78%_18%,rgba(77,127,224,.09),transparent_34%)]"/><div className="relative flex h-full flex-col"><div className="flex items-center justify-between"><span className="text-xs font-semibold uppercase tracking-[.16em] text-[var(--cyan)]">{item.type==="quiz"?"Knowledge check":"Live poll"}</span><span className="text-xs text-[#62707a]">Preview</span></div><h2 className="mt-auto max-w-4xl text-[clamp(2rem,4vw,4.7rem)] font-semibold leading-[1.02] tracking-[-.05em]">{item.question}</h2><div className="mt-auto grid gap-3 sm:grid-cols-2">{item.options.map((o,index)=><div key={o.id} className="flex items-center gap-3 rounded-xl border border-white/[.08] bg-white/[.035] px-4 py-3 text-sm text-[#b9c1c9]"><span className="grid size-7 place-items-center rounded-lg border border-white/[.08] text-[11px] font-semibold">{String.fromCharCode(65+index)}</span>{o.label}</div>)}</div></div></div>}
function Inspector({item,onUpdate,onDelete}:{item:DeckItem;onUpdate:(id:string,patch:Partial<DeckItem>)=>Promise<void>;onDelete:(id:string)=>Promise<void>}){const [title,setTitle]=useState(item.title);const [notes,setNotes]=useState(item.notes||"");const [question,setQuestion]=useState(item.question||"");const [options,setOptions]=useState(item.options);useEffect(()=>{setTitle(item.title);setNotes(item.notes||"");setQuestion(item.question||"");setOptions(item.options)},[item.id, item.title, item.notes, item.question, item.options]);return <div className="p-5"><div className="flex items-center justify-between"><div><div className="text-xs font-semibold uppercase tracking-[.13em] text-[#69747f]">Inspector</div><div className="mt-1 text-xs text-[#4f5963]">{item.type} item</div></div><MoreHorizontal className="size-4 text-[#5e6872]"/></div><div className="mt-7 space-y-5"><div className="space-y-2"><Label>Title</Label><Input value={title} onChange={e=>setTitle(e.target.value)}/></div>{item.type!=="slide"&&<><div className="space-y-2"><Label>Question</Label><Textarea value={question} onChange={e=>setQuestion(e.target.value)}/></div><div className="space-y-2"><Label>Options</Label>{options.map((o,index)=><Input key={o.id} value={o.label} onChange={e=>setOptions(current=>current.map(x=>x.id===o.id?{...x,label:e.target.value}:x))} className="mb-2" aria-label={`Option ${index+1}`}/>)}</div></>}<div className="space-y-2"><Label>Presenter note</Label><Textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Visible only to the presenter."/></div><Button className="w-full" variant="secondary" onClick={()=>void onUpdate(item.id,{title,notes,question:item.type!=="slide"?question:null,options})}><Save className="size-4"/>Save item</Button><Button className="w-full" variant="danger" onClick={()=>void onDelete(item.id)}><Trash2 className="size-4"/>Remove from deck</Button></div></div>}
function Modal({children,onClose}:{children:React.ReactNode;onClose:()=>void}){return <motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-[90] grid place-items-center bg-black/70 p-4 backdrop-blur-sm" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><motion.div initial={{opacity:0,y:18,scale:.98}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:12,scale:.98}} transition={{type:"spring",stiffness:320,damping:28}} className="cue-panel max-h-[90svh] w-full max-w-xl overflow-y-auto p-6 scrollbar-thin"><div className="mb-2 flex justify-end"><button onClick={onClose} aria-label="Close dialog" className="text-[#6c7680] hover:text-white"><X className="size-4"/></button></div>{children}</motion.div></motion.div>}
