"use client";
import { useEffect, useState } from "react";
import { BarChart3, Download, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Spinner } from "@/components/ui/spinner";
import { StatCard } from "@/components/patterns/stat-card";

type Report={deckTitle:string;attendeeCount:number;startedAt:string;endedAt:string|null;moments:{itemId:string;type:string;question:string;totalResponses:number;participationRate:number;options:{label:string;count:number;isCorrect?:boolean}[]}[]};
export function ReportPanel({code,token}:{code:string;token:string}){const [report,setReport]=useState<Report|null>(null);const [error,setError]=useState<string|null>(null);useEffect(()=>{fetch(`/api/live/${code}/report?token=${encodeURIComponent(token)}`).then(r=>r.json()).then(body=>body.ok?setReport(body.data):setError(body.error)).catch(()=>setError("Could not load report."))},[code,token]);function exportCsv(){if(!report)return;const rows=[["Question","Type","Responses","Participation","Option","Votes"],...report.moments.flatMap(m=>m.options.map(o=>[m.question,m.type,String(m.totalResponses),`${m.participationRate}%`,o.label,String(o.count)]))];const csv=rows.map(row=>row.map(cell=>`"${cell.replaceAll('"','""')}"`).join(",")).join("\n");const objectUrl=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=objectUrl;a.download=`cuepop-${code}-report.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(objectUrl),0)}
 if(error)return <div className="text-sm text-[var(--color-danger)]">{error}</div>;if(!report)return <div className="cue-body-sm flex items-center gap-2"><Spinner/>Preparing report…</div>;return <div><div className="grid grid-cols-2 gap-3"><StatCard icon={Users} value={report.attendeeCount} label="Attendees joined"/><StatCard icon={BarChart3} value={report.moments.length} label="Live moments" tone="accent"/></div><div className="mt-5 space-y-3">{report.moments.map(moment=><div key={moment.itemId} className="rounded-2xl border border-[var(--color-border)] bg-white/[.025] p-4"><div className="flex items-start justify-between gap-4"><div className="text-sm font-medium leading-6">{moment.question}</div><span className="shrink-0 text-sm font-semibold text-[var(--color-primary-hover)]">{moment.participationRate}%</span></div><div className="cue-caption mt-3 normal-case tracking-normal">{moment.totalResponses} responses</div></div>)}</div><Button className="mt-5 w-full" variant="secondary" onClick={exportCsv}><Download className="size-4"/>Export CSV</Button></div>}
