"use client";
import { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowUpRight, CalendarDays, ImageIcon, LoaderCircle, MoreHorizontal, Plus, Radio, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { toast } from "@/components/ui/toaster";
import type { Deck } from "@/lib/schema";
import { formatDate } from "@/lib/utils";

export function WorkspaceClient({ initialDecks }: { initialDecks: Deck[] }) {
 const router=useRouter(); const [decks,setDecks]=useState(initialDecks); const [creating,setCreating]=useState(false); const [title,setTitle]=useState("");
 async function createDeck(e:React.FormEvent){ e.preventDefault(); if(!title.trim())return; setCreating(true); const res=await fetch("/api/decks",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({title})}); const body=await res.json(); setCreating(false); if(!res.ok){toast({title:"Could not create deck",description:body.error,tone:"error"});return;} setDecks([body.data,...decks]); setTitle(""); router.push(`/workspace/decks/${body.data.id}`); }
 return <div className="mx-auto max-w-7xl">
  <div className="flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><div><p className="cue-eyebrow">Your presentation workspace</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.045em] md:text-5xl">Build once. Run the room.</h1><p className="mt-4 max-w-2xl text-[15px] leading-7 text-[#89939e]">Upload image slides, place audience moments exactly where they belong and rehearse all four live surfaces before the event.</p></div><form onSubmit={createDeck} className="flex w-full max-w-md gap-2"><Input value={title} onChange={(e)=>setTitle(e.target.value)} placeholder="New deck title"/><Button variant="accent" disabled={creating || !title.trim()}>{creating?<LoaderCircle className="size-4 animate-spin"/>:<Plus className="size-4"/>}Create deck</Button></form></div>
  <div className="mt-10 grid gap-4 sm:grid-cols-3"><Stat icon={ImageIcon} value={decks.length} label="Decks"/><Stat icon={Radio} value="Ready" label="Realtime room"/><Stat icon={Sparkles} value="3" label="Keepsake designs"/></div>
  <section className="mt-12"><div className="flex items-center justify-between"><div><h2 className="text-xl font-semibold tracking-[-.025em]">Recent decks</h2><p className="mt-1 text-sm text-[#717c87]">Continue editing or start a live rehearsal.</p></div></div>
   {decks.length===0?<div className="mt-6 cue-panel grid min-h-64 place-items-center p-8 text-center"><div><div className="mx-auto grid size-12 place-items-center rounded-2xl border border-white/[.08] bg-white/[.04]"><Plus className="size-5 text-[var(--cyan)]"/></div><h3 className="mt-4 font-semibold">Create your first live deck</h3><p className="mt-2 text-sm text-[#7d8792]">Start with a title, then upload images and insert a poll.</p></div></div>:
   <div className="mt-6 grid gap-4 lg:grid-cols-2">{decks.map((deck,index)=><Link href={`/workspace/decks/${deck.id}`} key={deck.id} className="group cue-hover-card cue-panel relative overflow-hidden p-5"><div className="absolute inset-y-0 right-0 w-40 bg-[radial-gradient(circle_at_70%_50%,rgba(77,127,224,.11),transparent_65%)] opacity-70"/><div className="relative flex gap-4"><div className="cue-hover-icon grid h-24 w-36 shrink-0 place-items-center overflow-hidden rounded-xl border border-white/[.07] bg-[#0a0d10]"><div className="relative h-full w-full"><div className="absolute inset-x-3 top-3 h-1.5 rounded-full bg-white/[.12]"/><div className="absolute left-3 top-8 h-8 w-14 rounded bg-[rgba(77,127,224,.18)]"/><div className="absolute right-3 top-8 h-8 w-10 rounded bg-white/[.06]"/><div className="absolute inset-x-3 bottom-3 h-1 rounded-full bg-white/[.08]"/></div></div><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><div><div className="text-[11px] font-semibold uppercase tracking-[.13em] text-[var(--cyan)]">{index===0?"Recently edited":"Draft"}</div><h3 className="mt-2 truncate text-lg font-semibold tracking-[-.025em]">{deck.title}</h3></div><MoreHorizontal className="size-4 text-[#6f7983]"/></div><p className="mt-2 line-clamp-2 text-sm leading-6 text-[#7f8994]">{deck.description || "Image-first deck ready for slides and live moments."}</p><div className="mt-4 flex items-center gap-4 text-xs text-[#68727d]"><span className="flex items-center gap-1.5"><CalendarDays className="size-3.5"/>{formatDate(deck.updatedAt)}</span><span className="ml-auto flex items-center gap-1 text-[#aeb7c0] group-hover:text-white">Open <ArrowUpRight className="cue-hover-arrow size-3.5"/></span></div></div></div></Link>)}</div>}
  </section>
 </div>;
}
function Stat({icon:Icon,value,label}:{icon:typeof ImageIcon;value:string|number;label:string}){return <Card className="flex items-center gap-4 p-4"><div className="grid size-10 place-items-center rounded-xl border border-white/[.07] bg-white/[.04]"><Icon className="size-4 text-[var(--cyan)]"/></div><div><div className="text-xl font-semibold tracking-[-.03em]">{value}</div><div className="text-xs text-[#727d88]">{label}</div></div></Card>}
