"use client";
import { useEffect, useMemo, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { Check, CheckCircle2, LoaderCircle, Lock, Radio, Sparkles, WifiOff } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { toast } from "@/components/ui/toaster";
import { CuePopLogo } from "@/components/logo";
import { KeepsakeDesigner } from "@/components/keepsake-designer";
import { useRoom } from "@/components/live/use-room";

function deviceKey(code:string){return `cuepop:${code}:device`}
function attendeeKey(code:string){return `cuepop:${code}:attendee`}
function nameKey(code:string){return `cuepop:${code}:name`}

export function AttendeeView({ code }: { code:string }) {
 const {snapshot,connected,error,socket}=useRoom(code); const [name,setName]=useState(""); const [attendeeId,setAttendeeId]=useState<string|null>(null); const [joining,setJoining]=useState(false); const [answers,setAnswers]=useState({runVersion:0,itemIds:[] as string[]}); const [selection,setSelection]=useState<{runVersion:number;itemId:string;optionId:string}|null>(null); const [voting,setVoting]=useState(false);
 useEffect(()=>{
   if(!socket)return;
   const restoreAttendee=()=>{const storedName=localStorage.getItem(nameKey(code))||"";setName(storedName);const storedDevice=localStorage.getItem(deviceKey(code));const storedAttendee=localStorage.getItem(attendeeKey(code));if(storedDevice&&storedAttendee){socket.emit("attendee:join",{code,deviceId:storedDevice,name:storedName||undefined},(ack:any)=>{if(ack?.ok){setAttendeeId(ack.data.attendeeId);localStorage.setItem(attendeeKey(code),ack.data.attendeeId);setAnswers({runVersion:ack.data.snapshot.runVersion,itemIds:ack.data.answeredItemIds||[]})}else{localStorage.removeItem(attendeeKey(code))}})}};
     restoreAttendee();socket.on("connect",restoreAttendee);return()=>{socket.off("connect",restoreAttendee)};
 },[code,socket]);
 const displayName=useMemo(()=>name.trim()||"Guest attendee",[name]);
 async function join(e?:React.FormEvent){e?.preventDefault();if(!socket){toast({title:"Still connecting",description:"Wait a moment and try again.",tone:"error"});return}setJoining(true);let deviceId=localStorage.getItem(deviceKey(code));if(!deviceId){deviceId=crypto.randomUUID();localStorage.setItem(deviceKey(code),deviceId)}socket.emit("attendee:join",{code,deviceId,name:name.trim()||undefined},(ack:any)=>{setJoining(false);if(!ack?.ok){toast({title:"Could not join",description:ack?.error||"Try again.",tone:"error"});return}setAttendeeId(ack.data.attendeeId);localStorage.setItem(attendeeKey(code),ack.data.attendeeId);localStorage.setItem(nameKey(code),name.trim());setAnswers({runVersion:ack.data.snapshot.runVersion,itemIds:ack.data.answeredItemIds||[]});toast({title:"You joined the room",description:"Keep this page open during the session."})})}
 function vote(){const selected=selection&&selection.runVersion===snapshot?.runVersion&&selection.itemId===snapshot?.currentItem?.id?selection.optionId:null;if(!socket||!snapshot?.currentItem||!attendeeId||!selected)return;setVoting(true);socket.emit("attendee:vote",{code,attendeeId,itemId:snapshot.currentItem.id,optionId:selected},(ack:any)=>{setVoting(false);if(!ack?.ok){toast({title:"Answer not submitted",description:ack?.error||"Try again.",tone:"error"});return}setAnswers(current=>({runVersion:snapshot.runVersion,itemIds:current.runVersion===snapshot.runVersion&&current.itemIds.includes(snapshot.currentItem!.id)?current.itemIds:[...current.itemIds,snapshot.currentItem!.id]}));toast({title:"Answer submitted"})})}
 if(error&&!snapshot)return <MobileShell><StateIcon icon={WifiOff}/><h1 className="mt-5 text-2xl font-semibold">Room unavailable</h1><p className="mt-2 text-sm leading-6 text-[var(--color-foreground-muted)]">{error}</p></MobileShell>;
 if(!snapshot)return <MobileShell><LoaderCircle className="mx-auto size-7 animate-spin text-[var(--cyan-strong)]"/><p className="mt-4 text-sm text-[var(--color-foreground-muted)]">Connecting to room {code}…</p></MobileShell>;
 if(!attendeeId)return <MobileShell><div className="flex items-center justify-between"><CuePopLogo/><span className="rounded-full border border-[var(--color-border)] px-3 py-1 text-xs text-[var(--color-foreground-muted)]">{code}</span></div><div className="mt-16"><p className="cue-eyebrow">{snapshot.deckTitle}</p><h1 className="mt-4 text-4xl font-semibold leading-[1] tracking-[-.05em]">Join the room.</h1><p className="mt-4 text-sm leading-6 text-[var(--color-foreground-muted)]">No account needed. Your name is optional and never appears in projector results.</p>{snapshot.joinLocked?<div className="mt-8 rounded-2xl border border-[var(--color-border)] bg-white/[.03] p-5 text-center"><Lock className="mx-auto size-5 text-[var(--color-warning)]"/><div className="mt-3 font-semibold">Joining is locked</div><p className="mt-1 text-sm text-[var(--color-foreground-muted)]">The presenter may reopen it.</p></div>:<form onSubmit={join} className="mt-8 space-y-3"><Input value={name} onChange={e=>setName(e.target.value)} placeholder="Your name (optional)" autoComplete="name"/><Button className="w-full" size="lg" variant="primary" disabled={joining}>{joining?<LoaderCircle className="size-4 animate-spin"/>:<Radio className="size-4"/>}Join session</Button></form>}</div></MobileShell>;
 const item=snapshot.currentItem; const submitted=Boolean(item&&answers.runVersion===snapshot.runVersion&&answers.itemIds.includes(item.id)); const selected=selection?.runVersion===snapshot.runVersion&&selection.itemId===item?.id?selection.optionId:null;
 return <MobileShell full><div className="flex items-center justify-between"><CuePopLogo/><div className="flex items-center gap-2 text-xs text-[var(--color-foreground-muted)]"><span className={`size-2 rounded-full ${connected?"bg-[var(--color-success)]":"bg-[var(--color-warning)]"}`}/>{connected?"Connected":"Reconnecting"}</div></div><AnimatePresence mode="wait">
  {snapshot.status==="ended"?<motion.div key="ended" initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} className="mt-9"><div className="text-center"><CheckCircle2 className="mx-auto size-10 text-[var(--cyan-strong)]"/><p className="mt-5 cue-eyebrow">Session complete</p><h1 className="mt-3 text-3xl font-semibold tracking-[-.045em]">Thanks for joining in.</h1><p className="mt-3 text-sm leading-6 text-[var(--color-foreground-muted)]">Choose a card and keep a small record of the room.</p></div><div className="mt-8"><KeepsakeDesigner name={displayName} deckTitle={snapshot.deckTitle} code={code} allowedThemes={snapshot.keepsakeThemes}/></div></motion.div>:
  snapshot.status==="active"&&item&&item.type!=="slide"?<motion.div key={item.id+"active"} initial={{opacity:0,y:14}} animate={{opacity:1,y:0}} className="mt-10"><div className="flex items-center justify-between"><span className="cue-eyebrow">{item.type==="quiz"?"Knowledge check":"Live poll"}</span><span className="text-xs text-[var(--color-foreground-muted)]">{snapshot.responseCount} responded</span></div><h1 className="mt-5 text-[2rem] font-semibold leading-[1.07] tracking-[-.045em]">{item.question}</h1>{submitted?<div className="mt-10 rounded-2xl border border-[rgba(110,215,178,.18)] bg-[rgba(110,215,178,.055)] p-7 text-center"><div className="mx-auto grid size-12 place-items-center rounded-full bg-[rgba(110,215,178,.12)]"><Check className="size-5 text-[var(--color-success)]"/></div><h2 className="mt-4 font-semibold">Answer submitted</h2><p className="mt-2 text-sm leading-6 text-[var(--color-foreground-muted)]">The presenter controls when the room sees the result.</p></div>:<><div className="mt-7 space-y-3">{item.options.map((option,index)=><button key={option.id} onClick={()=>setSelection({runVersion:snapshot.runVersion,itemId:item.id,optionId:option.id})} className={`flex w-full items-center gap-3 rounded-2xl border p-4 text-left transition ${selected===option.id?"border-[var(--color-primary-hover)] bg-[rgba(65,105,225,.075)]":"border-[var(--color-border)] bg-white/[.025]"}`}><span className={`grid size-9 shrink-0 place-items-center rounded-xl border text-xs font-semibold ${selected===option.id?"border-[rgba(65,105,215,.4)] text-[var(--cyan-strong)]":"border-[var(--color-border)] text-[var(--color-foreground-muted)]"}`}>{String.fromCharCode(65+index)}</span><span className="text-sm leading-6">{option.label}</span></button>)}</div><Button className="mt-5 w-full" size="lg" variant="primary" disabled={!selected||voting} onClick={vote}>{voting?<LoaderCircle className="size-4 animate-spin"/>:<Check className="size-4"/>}Submit answer</Button></>}</motion.div>:
  snapshot.status==="revealed"&&item&&item.type!=="slide"?<motion.div key={item.id+"reveal"} initial={{opacity:0,y:14}} animate={{opacity:1,y:0}} className="mt-10"><p className="cue-eyebrow">Room result</p><h1 className="mt-4 text-3xl font-semibold leading-[1.08] tracking-[-.045em]">{item.question}</h1><div className="mt-7 space-y-3">{snapshot.results?.map((result,index)=><div key={result.optionId} className={`relative overflow-hidden rounded-2xl border p-4 ${result.isCorrect?"border-[rgba(110,215,178,.28)]":"border-[var(--color-border)]"}`}><div className={`absolute inset-y-0 left-0 ${result.isCorrect?"bg-[rgba(110,215,178,.12)]":"bg-[rgba(65,105,225,.08)]"}`} style={{width:`${Math.max(result.percent,2)}%`}}/><div className="relative flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl border border-white/[.09] text-xs font-semibold">{String.fromCharCode(65+index)}</span><span className="min-w-0 flex-1 text-sm">{result.label}</span>{result.isCorrect&&<CheckCircle2 className="size-4 text-[var(--color-success)]"/>}<span className="font-semibold">{result.percent}%</span></div></div>)}</div></motion.div>:
  <motion.div key={(item?.id||"wait")+snapshot.status} initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} className="grid min-h-[70svh] place-items-center text-center"><div><div className="relative mx-auto grid size-20 place-items-center rounded-full border border-[var(--color-border)] bg-white/[.03]"><div className="absolute inset-2 rounded-full border border-[rgba(65,105,225,.14)] animate-cue-pulse"/><Sparkles className="size-6 text-[var(--cyan-strong)]"/></div><p className="mt-7 cue-eyebrow">{snapshot.deckTitle}</p><h1 className="mt-4 text-3xl font-semibold tracking-[-.045em]">{snapshot.status==="closed"?"Voting is closed.":item?.type!=="slide"&&item?"A question is coming.":"Stay with the room."}</h1><p className="mx-auto mt-3 max-w-sm text-sm leading-6 text-[var(--color-foreground-muted)]">{snapshot.status==="closed"?(submitted?"Your response is in. The presenter can reveal the room result next.":"The response window has closed. Stay here for the room result."):"The next live moment will appear here automatically."}</p></div></motion.div>}
 </AnimatePresence></MobileShell>
}
function MobileShell({children,full=false}:{children:React.ReactNode;full?:boolean}){return <main className="min-h-svh bg-[var(--color-surface)] px-5 py-6 text-white"><div className={`mx-auto w-full max-w-md ${full?"pb-10":""}`}>{children}</div></main>}
function StateIcon({icon:Icon}:{icon:typeof WifiOff}){return <div className="mx-auto grid size-12 place-items-center rounded-2xl border border-[var(--color-border)] bg-white/[.035]"><Icon className="size-5 text-[var(--cyan-strong)]"/></div>}
