"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { AnimatePresence, motion } from "framer-motion";
import { ArrowLeft, ArrowRight, BarChart3, ChevronLeft, ChevronRight, CircleStop, Copy, ExternalLink, Eye, Lock, Monitor, Play, QrCode, Radio, RotateCcw, Smartphone, Unlock, Users, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { toast } from "@/components/ui/toaster";
import { QRPanel } from "@/components/live/qr-panel";
import { ReportPanel } from "@/components/report-panel";
import { useRoom } from "@/components/live/use-room";
import type { DeckItem } from "@/lib/schema";
import type { HostCommandType } from "@/lib/live/types";

export function PresenterConsole({code,token}:{code:string;token:string}){const {snapshot,connected,socket}=useRoom(code);const [items,setItems]=useState<DeckItem[]>([]);const [loading,setLoading]=useState(true);const [accessError,setAccessError]=useState<string|null>(null);const [panel,setPanel]=useState<null|"qr"|"report">("qr");const [commanding,setCommanding]=useState(false);
 useEffect(()=>{if(!token){setAccessError("This presenter link is missing its private control token.");setLoading(false);return}fetch(`/api/live/${code}?token=${encodeURIComponent(token)}`).then(r=>r.json()).then(body=>{if(body.ok)setItems(body.data.items);else{setAccessError(body.error||"This presenter link is invalid.");toast({title:"Presenter link rejected",description:body.error,tone:"error"})}}).catch(()=>setAccessError("The presenter controls could not be loaded.")).finally(()=>setLoading(false))},[code,token]);
 const current=useMemo(()=>{if(!snapshot?.currentItem)return null;const found=items.find(i=>i.id===snapshot.currentItem?.id);return found||{...snapshot.currentItem,notes:null}},[snapshot?.currentItem,items]);
 function command(command:HostCommandType){if(!socket){toast({title:"Realtime connection unavailable",tone:"error"});return}setCommanding(true);socket.emit("host:command",{code,token,command},(ack:any)=>{setCommanding(false);if(!ack?.ok)toast({title:"Command rejected",description:ack?.error||"Try again.",tone:"error"})})}
 async function copy(path:string){const url=`${window.location.origin}${path}`;await navigator.clipboard.writeText(url);toast({title:"Link copied",description:url})}
 if(loading)return <div className="grid min-h-svh place-items-center bg-[#07090c] text-[#7f8993]">Preparing presenter controls…</div>;
 if(accessError)return <main className="grid min-h-svh place-items-center bg-[#07090c] p-6 text-center text-white"><div className="max-w-md"><Lock className="mx-auto size-8 text-[var(--warning)]"/><h1 className="mt-5 text-2xl font-semibold">Presenter access denied</h1><p className="mt-3 text-sm leading-6 text-[#84909a]">{accessError}</p><Button asChild className="mt-6" variant="secondary"><Link href="/workspace">Return to workspace</Link></Button></div></main>;
 if(!snapshot)return <div className="grid min-h-svh place-items-center bg-[#07090c] text-[#7f8993]">Connecting to the live room…</div>;
 const isMoment=current&&current.type!=="slide";const canPrev=snapshot.currentIndex>0;const canNext=snapshot.currentIndex<snapshot.totalItems-1;
 return <main className="min-h-svh bg-[#080a0d] text-white"><header className="flex h-16 items-center gap-3 border-b border-white/[.065] px-4 md:px-6"><Button asChild variant="ghost" size="icon"><Link href="/workspace" aria-label="Back to workspace"><ArrowLeft className="size-4"/></Link></Button><div className="min-w-0"><div className="truncate text-sm font-semibold">{snapshot.deckTitle}</div><div className="flex items-center gap-2 text-[11px] text-[#65707a]"><span className={`size-1.5 rounded-full ${connected?"bg-[var(--success)]":"bg-[var(--warning)]"}`}/>{connected?"Live room connected":"Reconnecting"} · {code}</div></div><div className="ml-auto flex items-center gap-2"><Button size="sm" variant="ghost" onClick={()=>setPanel(panel==="qr"?null:"qr")}><QrCode className="size-4"/><span className="hidden sm:inline">Join screen</span></Button><Button size="sm" variant="ghost" onClick={()=>setPanel(panel==="report"?null:"report")}><BarChart3 className="size-4"/><span className="hidden sm:inline">Report</span></Button><Button asChild size="sm" variant="secondary"><a href={`/stage/${code}`} target="_blank" rel="noreferrer"><Monitor className="size-4"/><span className="hidden sm:inline">Open stage</span></a></Button></div></header>
  <div className={`grid min-h-[calc(100svh-64px)] ${panel?"xl:grid-cols-[minmax(0,1fr)_360px]":""}`}><div className="grid min-w-0 lg:grid-cols-[minmax(0,1fr)_330px]"><section className="relative flex min-h-[52svh] items-center justify-center overflow-hidden bg-[#050608] p-5 md:p-8"><div className="absolute inset-0 cue-grid-noise opacity-25"/>{snapshot.status==="join"?<div className="relative cue-panel max-w-3xl p-8"><QRPanel code={code} attendeeCount={snapshot.attendeeCount}/></div>:current?.type==="slide"?<div className="relative aspect-video w-full max-w-5xl overflow-hidden rounded-2xl border border-white/[.09] bg-black"><img src={current.imageUrl||""} alt={current.title} className="h-full w-full object-contain"/></div>:current?<div className="relative w-full max-w-5xl rounded-2xl border border-white/[.09] bg-[#0a0d11] p-8 md:p-12"><div className="flex justify-between text-xs"><span className="font-semibold uppercase tracking-[.14em] text-[var(--cyan)]">{current.type}</span><span className="text-[#6f7a84]">{snapshot.responseCount}/{snapshot.attendeeCount} responded</span></div><h1 className="mt-7 text-[clamp(2rem,4vw,4.4rem)] font-semibold leading-[1.02] tracking-[-.05em]">{current.question}</h1>{snapshot.results?<div className="mt-8 space-y-3">{snapshot.results.map(r=><div key={r.optionId} className="relative overflow-hidden rounded-xl border border-white/[.08] p-4"><div className="absolute inset-y-0 left-0 bg-[rgba(77,127,224,.1)]" style={{width:`${r.percent}%`}}/><div className="relative flex justify-between gap-4"><span>{r.label}</span><b>{r.percent}%</b></div></div>)}</div>:<div className="mt-8 grid gap-3 sm:grid-cols-2">{current.options.map((o,index)=><div key={o.id} className="rounded-xl border border-white/[.08] bg-white/[.03] p-4 text-sm text-[#b9c2ca]"><span className="mr-3 text-[var(--cyan)]">{String.fromCharCode(65+index)}</span>{o.label}</div>)}</div>}</div>:<div className="relative text-center text-[#77828c]">Select a timeline item.</div>}</section>
   <aside className="border-t border-white/[.065] bg-[#090c10] p-5 lg:border-l lg:border-t-0"><div className="flex items-center justify-between"><div><div className="text-xs font-semibold uppercase tracking-[.14em] text-[#69747f]">Presenter controls</div><div className="mt-1 text-xs text-[#4f5a64]">Only visible to you</div></div><span className="rounded-full border border-white/[.08] bg-white/[.035] px-2.5 py-1 text-[11px] text-[#7f8993]">{snapshot.status}</span></div>
    <div className="mt-6 rounded-2xl border border-white/[.08] bg-white/[.025] p-4"><div className="text-[11px] uppercase tracking-[.13em] text-[#66717b]">Current item</div><div className="mt-2 text-sm font-semibold leading-6">{snapshot.status==="join"?"Dynamic join screen":current?.title||"No item selected"}</div>{current?.notes&&<p className="mt-3 text-xs leading-5 text-[#7c8791]">{current.notes}</p>}</div>
    <div className="mt-4 grid grid-cols-2 gap-2"><Button variant="secondary" disabled={!canPrev||commanding||snapshot.status==="join"||snapshot.status==="active"} onClick={()=>command("previous")}><ChevronLeft className="size-4"/>Previous</Button><Button variant="secondary" disabled={!canNext||commanding||snapshot.status==="join"||snapshot.status==="active"} onClick={()=>command("next")}>Next<ChevronRight className="size-4"/></Button></div>
    <div className="mt-2 space-y-2">{snapshot.status==="join"?<Button className="w-full" variant="accent" onClick={()=>command("start")}><Play className="size-4"/>Start first item</Button>:isMoment?<><Button className="w-full" variant="accent" disabled={snapshot.status!=="presenting"} onClick={()=>command("open")}><Radio className="size-4"/>Open voting</Button><div className="grid grid-cols-2 gap-2"><Button variant="secondary" disabled={snapshot.status!=="active"} onClick={()=>command("close")}><CircleStop className="size-4"/>Close</Button><Button variant="secondary" disabled={snapshot.status!=="closed"} onClick={()=>command("reveal")}><Eye className="size-4"/>Reveal</Button></div></>:<Button className="w-full" variant="secondary" disabled={!canNext} onClick={()=>command("next")}>Advance slide<ArrowRight className="size-4"/></Button>}</div>
    <div className="mt-6 border-t border-white/[.065] pt-5"><div className="flex items-center justify-between text-xs text-[#7b8690]"><span className="flex items-center gap-2"><Users className="size-4"/>{snapshot.attendeeCount} joined</span><button className="hover:text-white" onClick={()=>command(snapshot.joinLocked?"unlockJoin":"lockJoin")}>{snapshot.joinLocked?<span className="flex items-center gap-1.5"><Unlock className="size-3.5"/>Unlock joining</span>:<span className="flex items-center gap-1.5"><Lock className="size-3.5"/>Lock joining</span>}</button></div><Button className="mt-4 w-full" variant="danger" onClick={()=>confirm("End this live session?")&&command("end")}><CircleStop className="size-4"/>End session</Button><Button className="mt-2 w-full" variant="ghost" onClick={()=>command("showJoin")}><RotateCcw className="size-4"/>Return to join screen</Button></div>
    <div className="mt-6 rounded-2xl border border-white/[.07] bg-[#07090c] p-4"><div className="text-xs font-semibold">Phone remote</div><p className="mt-1 text-xs leading-5 text-[#6f7a84]">Open the compact controller on your phone.</p><div className="mt-3 flex gap-2"><Button asChild size="sm" variant="secondary" className="flex-1"><a href={`/remote/${code}?token=${encodeURIComponent(token)}`} target="_blank" rel="noreferrer"><Smartphone className="size-3.5"/>Open</a></Button><Button size="icon" variant="ghost" aria-label="Copy remote link" onClick={()=>copy(`/remote/${code}?token=${encodeURIComponent(token)}`)}><Copy className="size-3.5"/></Button></div></div>
   </aside></div>
   <AnimatePresence>{panel&&<motion.aside initial={{opacity:0,x:22}} animate={{opacity:1,x:0}} exit={{opacity:0,x:22}} className="border-l border-white/[.065] bg-[#080b0f] p-5"><div className="flex items-center justify-between"><h2 className="font-semibold">{panel==="qr"?"Audience join":"Session report"}</h2><button onClick={()=>setPanel(null)} aria-label="Close panel" className="text-[#68737d] hover:text-white"><X className="size-4"/></button></div><div className="mt-6">{panel==="qr"?<><QRPanel code={code} attendeeCount={snapshot.attendeeCount}/><div className="mt-6 space-y-2"><Button className="w-full" variant="secondary" onClick={()=>copy(`/join/${code}`)}><Copy className="size-4"/>Copy attendee link</Button><Button className="w-full" variant="secondary" asChild><a href={`/stage/${code}`} target="_blank" rel="noreferrer"><ExternalLink className="size-4"/>Open projector stage</a></Button></div></>:<ReportPanel code={code} token={token}/>}</div></motion.aside>}</AnimatePresence>
  </div>
 </main>}
