"use client";
import { AnimatePresence, motion } from "framer-motion";
import { CheckCircle2, Lock, Users } from "lucide-react";
import { useRoom } from "@/components/live/use-room";
import { QRPanel } from "@/components/live/qr-panel";

export function StageView({code}:{code:string}){const {snapshot,connected,error}=useRoom(code);if(error)return <StageMessage title="Room unavailable" copy={error}/>;if(!snapshot)return <StageMessage title="Connecting to CuePop" copy="Preparing the live stage…"/>;const item=snapshot.currentItem;return <main className="stage-shell relative overflow-hidden"><div className="absolute inset-0 cue-grid-noise opacity-20"/><div className="absolute -right-[15vw] -top-[20vw] size-[55vw] rounded-full bg-[rgba(65,105,225,.06)] blur-[120px]"/><div className="absolute left-6 top-5 z-20 flex items-center gap-2 text-xs text-[var(--color-foreground-subtle)]"><span className={`size-2 rounded-full ${connected?"bg-[var(--color-success)]":"bg-[var(--color-warning)]"}`}/>{connected?"Live":"Reconnecting"}</div><AnimatePresence mode="wait">
 {snapshot.status==="join"&&<motion.section key="join" className="stage-safe relative flex min-h-svh items-center justify-between gap-12 py-[7vh]" initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-12}}><div className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[.16em] text-[var(--cyan-strong)]">{snapshot.deckTitle}</p><h1 className="mt-6 text-[clamp(4rem,8vw,9rem)] font-semibold leading-[.87] tracking-[-.07em]">The room<br/>starts here.</h1><p className="mt-8 max-w-2xl text-[clamp(1.2rem,2vw,2rem)] leading-relaxed text-[var(--color-foreground-muted)]">{snapshot.waitingMessage}</p>{snapshot.joinLocked&&<div className="mt-7 inline-flex items-center gap-2 rounded-full border border-[var(--color-border-strong)] bg-white/[.04] px-4 py-2 text-sm text-[var(--color-foreground-muted)]"><Lock className="size-4"/>Joining is locked</div>}</div><div className="cue-panel shrink-0 p-8"><QRPanel code={code} attendeeCount={snapshot.attendeeCount}/></div></motion.section>}
 {snapshot.status!=="join"&&snapshot.status!=="ended"&&item?.type==="slide"&&<motion.section key={item.id+snapshot.status} className="grid min-h-svh place-items-center p-[4vw]" initial={{opacity:0,scale:.99}} animate={{opacity:1,scale:1}} exit={{opacity:0,scale:1.01}}><div className="relative aspect-video w-full overflow-hidden rounded-[2vw] border border-[var(--color-border)] bg-black shadow-[0_50px_180px_rgba(0,0,0,.8)]"><img src={item.imageUrl||""} alt={item.title} className="h-full w-full object-contain"/></div></motion.section>}
 {snapshot.status!=="join"&&snapshot.status!=="ended"&&item&&item.type!=="slide"&&<motion.section key={item.id+snapshot.status} className="stage-safe flex min-h-svh flex-col justify-center py-[8vh]" initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-16}}><div className="flex items-center justify-between"><span className="text-sm font-semibold uppercase tracking-[.16em] text-[var(--cyan-strong)]">{item.type==="quiz"?"Knowledge check":"Live poll"}</span><span className="flex items-center gap-2 text-lg text-[var(--color-foreground-muted)]"><Users className="size-5"/>{snapshot.responseCount} / {snapshot.attendeeCount} responded</span></div><h1 className="mt-[5vh] max-w-[1300px] text-[clamp(3.4rem,6.4vw,7.4rem)] font-semibold leading-[.97] tracking-[-.06em]">{item.question}</h1>{snapshot.status==="revealed"&&snapshot.results?<Results results={snapshot.results}/>:<div className="mt-[7vh] grid gap-4 sm:grid-cols-2">{item.options.map((option,index)=><div key={option.id} className="flex items-center gap-5 rounded-2xl border border-[var(--color-border-strong)] bg-white/[.035] p-5 text-[clamp(1.1rem,1.8vw,1.8rem)] text-[var(--color-foreground)]"><span className="grid size-12 shrink-0 place-items-center rounded-xl border border-[var(--color-border-strong)] text-base font-semibold">{String.fromCharCode(65+index)}</span>{option.label}</div>)}</div>}<div className="mt-[5vh] text-xl text-[var(--color-foreground-subtle)]">{snapshot.status==="presenting"&&"The presenter will open voting in a moment."}{snapshot.status==="active"&&"Voting is open on attendee phones."}{snapshot.status==="closed"&&"Voting closed. Results are ready to reveal."}</div></motion.section>}
 {snapshot.status==="ended"&&<motion.section key="ended" className="stage-safe grid min-h-svh place-items-center text-center" initial={{opacity:0}} animate={{opacity:1}}><div><CheckCircle2 className="mx-auto size-16 text-[var(--cyan-strong)]"/><p className="mt-8 text-sm font-semibold uppercase tracking-[.16em] text-[var(--cyan-strong)]">Session complete</p><h1 className="mt-5 text-[clamp(4rem,9vw,9rem)] font-semibold leading-[.88] tracking-[-.07em]">Thanks for<br/>joining in.</h1><p className="mt-8 text-2xl text-[var(--color-foreground-muted)]">Your keepsake is ready on your phone.</p></div></motion.section>}
 </AnimatePresence></main>}
function Results({results}:{results:NonNullable<import("@/lib/live/types").RoomSnapshot["results"]>}){return <div className="mt-[7vh] space-y-4">{[...results].sort((a,b)=>b.count-a.count).map((result,index)=><div key={result.optionId} className={`relative overflow-hidden rounded-2xl border p-5 ${result.isCorrect?"border-[rgba(110,215,178,.32)]":"border-[var(--color-border)]"}`}><motion.div className={`absolute inset-y-0 left-0 ${result.isCorrect?"bg-[rgba(110,215,178,.13)]":"bg-[rgba(65,105,225,.1)]"}`} initial={{width:0}} animate={{width:`${Math.max(result.percent,2)}%`}} transition={{duration:.8,delay:index*.08}}/><div className="relative flex items-center gap-5"><span className="grid size-12 place-items-center rounded-xl border border-[var(--color-border-strong)] text-base font-semibold">{String.fromCharCode(65+results.findIndex(r=>r.optionId===result.optionId))}</span><span className="flex-1 text-[clamp(1.15rem,2vw,2rem)]">{result.label}</span>{result.isCorrect&&<CheckCircle2 className="size-7 text-[var(--color-success)]"/>}<span className="text-[clamp(1.6rem,3vw,3rem)] font-semibold tracking-[-.04em]">{result.percent}%</span></div></div>)}</div>}
function StageMessage({title,copy}:{title:string;copy:string}){return <main className="stage-shell grid min-h-svh place-items-center text-center"><div><div className="mx-auto size-3 rounded-full bg-[var(--color-primary)] animate-cue-pulse"/><h1 className="mt-6 text-4xl font-semibold tracking-[-.04em]">{title}</h1><p className="mt-3 text-lg text-[var(--color-foreground-subtle)]">{copy}</p></div></main>}
